// <auto-generated />
using System;
using LMSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMSystem.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260729044204_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMSystem.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Andrew Hunt and David Thomas",
                            ISBN = "978-0201616224",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2021, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Robert C. Martin",
                            ISBN = "978-0132350884",
                            IsAvailable = false,
                            PublishedDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Design Pattern using C#"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Pranaya Kumar Rout",
                            ISBN = "978-0451616235",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2022, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mastering ASP.NET Core"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Rakesh Kumar",
                            ISBN = "978-4562350123",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2020, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "SQL Server with DBA"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Robert C. Martin",
                            ISBN = "978-0132350702",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2008, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Clean Code"
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Thomas H. Cormen",
                            ISBN = "978-0262033848",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2009, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Introduction to Algorithms"
                        },
                        new
                        {
                            BookId = 7,
                            Author = "Kyle Simpson",
                            ISBN = "978-1091210095",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2020, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "You Don't Know JS Yet"
                        },
                        new
                        {
                            BookId = 8,
                            Author = "Martin Fowler",
                            ISBN = "978-0134757599",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2018, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Refactoring"
                        });
                });

            modelBuilder.Entity("LMSystem.Models.BorrowRecord", b =>
                {
                    b.Property<int>("BorrowRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BorrowRecordId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BorrowerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BorrowRecordId");

                    b.HasIndex("BookId");

                    b.ToTable("BorrowRecords");

                    b.HasData(
                        new
                        {
                            BorrowRecordId = 1,
                            BookId = 2,
                            BorrowDate = new DateTime(2026, 7, 27, 4, 42, 4, 157, DateTimeKind.Utc).AddTicks(3305),
                            BorrowerEmail = "priya.sharma@example.com",
                            BorrowerName = "Priya Sharma",
                            Phone = "+91 98765 43210"
                        },
                        new
                        {
                            BorrowRecordId = 2,
                            BookId = 5,
                            BorrowDate = new DateTime(2026, 7, 19, 4, 42, 4, 157, DateTimeKind.Utc).AddTicks(3313),
                            BorrowerEmail = "arjun.mehta@example.com",
                            BorrowerName = "Arjun Mehta",
                            Phone = "+91 91234 56789",
                            ReturnDate = new DateTime(2026, 7, 26, 4, 42, 4, 157, DateTimeKind.Utc).AddTicks(3313)
                        });
                });

            modelBuilder.Entity("LMSystem.Models.Librarian", b =>
                {
                    b.Property<int>("LibrarianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LibrarianId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LibrarianId");

                    b.ToTable("Librarians");

                    b.HasData(
                        new
                        {
                            LibrarianId = 1,
                            Age = 34,
                            Name = "Meera Joshi",
                            Phone = "+91 90000 77777"
                        },
                        new
                        {
                            LibrarianId = 2,
                            Age = 41,
                            Name = "Sanjay Rao",
                            Phone = "+91 90000 88888"
                        },
                        new
                        {
                            LibrarianId = 3,
                            Age = 29,
                            Name = "Neha Bhatt",
                            Phone = "+91 90000 99999"
                        },
                        new
                        {
                            LibrarianId = 4,
                            Age = 38,
                            Name = "Arvind Menon",
                            Phone = "+91 90000 12121"
                        },
                        new
                        {
                            LibrarianId = 5,
                            Age = 45,
                            Name = "Pooja Iyer",
                            Phone = "+91 90000 13131"
                        },
                        new
                        {
                            LibrarianId = 6,
                            Age = 31,
                            Name = "Farhan Sheikh",
                            Phone = "+91 90000 14141"
                        });
                });

            modelBuilder.Entity("LMSystem.Models.LoginUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("LoginUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "12345",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "myc546",
                            Username = "mycodingproject"
                        },
                        new
                        {
                            Id = 3,
                            Password = "myc",
                            Username = "my"
                        });
                });

            modelBuilder.Entity("LMSystem.Models.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Publications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Global Media Group",
                            Title = "The Daily Times",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "WallSt Press",
                            Title = "Financial Chronicle",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Silicon Valley Pubs",
                            Title = "Tech Weekly News",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "City Press House",
                            Title = "Metro Morning Post",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            IsAvailable = false,
                            PublishedDate = new DateTime(2026, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Global Media Group",
                            Title = "Saturday Sports Herald",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "NatGeo Society",
                            Title = "National Geographic Vol 45",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Conde Nast",
                            Title = "Vogue Fashion Summer",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            IsAvailable = false,
                            PublishedDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Forbes Media",
                            Title = "Forbes Business 30 Under 30",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Future US",
                            Title = "PC Gamer Ultimate",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Springer Nature",
                            Title = "Scientific American",
                            Type = 1
                        });
                });

            modelBuilder.Entity("LMSystem.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Email = "aditi.verma@example.com",
                            Phone = "+91 90000 11111",
                            StudentName = "Aditi Verma"
                        },
                        new
                        {
                            StudentId = 2,
                            Email = "rohan.gupta@example.com",
                            Phone = "+91 90000 22222",
                            StudentName = "Rohan Gupta"
                        },
                        new
                        {
                            StudentId = 3,
                            Email = "sneha.kapoor@example.com",
                            Phone = "+91 90000 33333",
                            StudentName = "Sneha Kapoor"
                        },
                        new
                        {
                            StudentId = 4,
                            Email = "karan.malhotra@example.com",
                            Phone = "+91 90000 44444",
                            StudentName = "Karan Malhotra"
                        },
                        new
                        {
                            StudentId = 5,
                            Email = "isha.nair@example.com",
                            Phone = "+91 90000 55555",
                            StudentName = "Isha Nair"
                        },
                        new
                        {
                            StudentId = 6,
                            Email = "vikram.singh@example.com",
                            Phone = "+91 90000 66666",
                            StudentName = "Vikram Singh"
                        });
                });

            modelBuilder.Entity("LMSystem.Models.BorrowRecord", b =>
                {
                    b.HasOne("LMSystem.Models.Book", "Book")
                        .WithMany("BorrowRecords")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LMSystem.Models.Book", b =>
                {
                    b.Navigation("BorrowRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
